# Generated by Django 5.0.6 on 2024-07-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coursename', models.CharField(max_length=100)),
                ('Institutename', models.CharField(max_length=200)),
                ('Details', models.CharField(max_length=500)),
                ('Language', models.CharField(max_length=100)),
                ('Coursefee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Duration', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
