# Generated by Django 5.0.6 on 2024-05-24 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseshare_app', '0001_initial'),
        ('user_app', '0002_educator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='Educator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user_app.educator'),
        ),
    ]
