# Generated by Django 5.0.6 on 2024-07-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseshare_app', '0002_courselist_educator_courselist_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselist',
            name='Educator',
        ),
        migrations.AddField(
            model_name='courselist',
            name='EducatorName',
            field=models.CharField(default='Default Educator', max_length=150),
        ),
    ]
